import os
from pathlib import Path
from typing import Callable

from dotenv import load_dotenv
from google import genai
from google.genai import types


TRANSCRIPTION_MODEL = "gemini-2.5-flash"
MAX_AUDIO_BYTES = 10 * 1024 * 1024
SUPPORTED_AUDIO_EXTENSIONS = {
    ".flac", ".m4a", ".mp3", ".mp4", ".mpeg",
    ".mpga", ".ogg", ".wav", ".webm",
}
TranscriptGenerator = Callable[[bytes, str, str], str]


class AudioTranscriptionError(RuntimeError):
    pass


def validate_audio(filename: str, audio_bytes: bytes) -> None:
    if Path(filename).suffix.lower() not in SUPPORTED_AUDIO_EXTENSIONS:
        raise ValueError("지원하지 않는 오디오 파일 형식입니다")
    if not audio_bytes:
        raise ValueError("오디오 파일이 비어 있습니다")
    if len(audio_bytes) > MAX_AUDIO_BYTES:
        raise ValueError("오디오 파일은 10MB 이하여야 합니다")


def generate_gemini_transcript(
    audio_bytes: bytes,
    content_type: str,
    language: str,
) -> str:
    load_dotenv()
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise AudioTranscriptionError(".env 파일에 GEMINI_API_KEY가 없습니다")

    client = genai.Client(api_key=api_key)
    prompt = (
        f"이 오디오에서 사람이 말한 내용을 {language} 텍스트로 정확히 전사하세요. "
        "설명, 따옴표, 화자 표기 없이 말한 내용만 출력하세요. "
        "말소리가 없다면 빈 문자열만 출력하세요."
    )
    try:
        response = client.models.generate_content(
            model=TRANSCRIPTION_MODEL,
            contents=[
                prompt,
                types.Part.from_bytes(
                    data=audio_bytes,
                    mime_type=content_type,
                ),
            ],
        )
    except Exception as error:
        raise AudioTranscriptionError(
            "Gemini 오디오 전사 요청에 실패했습니다"
        ) from error

    return str(response.text or "").strip()


def transcribe_audio(
    *,
    filename: str,
    content_type: str,
    audio_bytes: bytes,
    language: str = "ko",
    generator: TranscriptGenerator | None = None,
) -> str:
    """Validate uploaded audio and return a transcript generated by Gemini."""
    validate_audio(filename, audio_bytes)
    transcript_generator = generator or generate_gemini_transcript
    transcript = transcript_generator(audio_bytes, content_type, language).strip()
    if not transcript:
        raise AudioTranscriptionError("Gemini가 빈 transcript를 반환했습니다")
    return transcript
